# Pandas

In [ ]:
#Used for data analysis, and it has two data types: Series & DataFrame

In [ ]:
#Series: Has a number of rows, but only one column
#DataFrame: Has a number of rows, and a number of columns

In [ ]:
#Creating a simple series
import pandas as pd
values = [100,200,300,400,500]
val = pd.Series(values)
val

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [ ]:
import pandas as pd
val = pd.Series(values,index=['a','b','c','d','e'])
print(val,'\n')
type(val)

a    100
b    200
c    300
d    400
e    500
dtype: int64

pandas.core.series.Series

In [ ]:
#Nested List Into Series
a = [[1,2,3],[4,5,6]]
ser = pd.Series(a)
print(ser)

0    [1, 2, 3]
1    [4, 5, 6]
dtype: object

In [ ]:
#DrawBack of Series: Nested Lists with clubbed values are mapped to one index value

In [ ]:
#Convert a list into a dataframe
v = [10,20,30,40,50]
df = pd.DataFrame(v)
df

    0
0  10
1  20
2  30
3  40
4  50

In [ ]:
v = [100,200,300,400,500]
indexes=['a','b','c','d','e']
dat = pd.DataFrame(v, index = indexes, columns = ['Numbers'])
dat

   Numbers
a      100
b      200
c      300
d      400
e      500

In [ ]:
#Multiple List Into DataFrame

v = [100,200,300,400,500]
name = ['John','Bajal','Laya','Ramya','Pannu']
List_of_list = [name,v]
da = pd.DataFrame(List_of_list)
print(da)

      0      1     2      3      4
0  John  Bajal  Laya  Ramya  Pannu
1   100    200   300    400    500

In [ ]:
#Transpose of a DataFrame (Converting Into a Vertical Format)

v = [100,200,300,400,500]
name = ['John','Bajal','Laya','Ramya','Pannu']
List_of_list = [name,v]
da = pd.DataFrame(List_of_list)
dun = da.transpose()
dun.columns = ['Name','Values']
print(dun)

    Name Values
0   John    100
1  Bajal    200
2   Laya    300
3  Ramya    400
4  Pannu    500

In [ ]:
#List of List Into a DataFrame
list_o_list = [['Raj',100],['Yash',99],['Sam',98]]
data = pd.DataFrame(list_o_list)
print(data)

      0    1
0   Raj  100
1  Yash   99
2   Sam   98

In [ ]:
#Dictionary Into a DataFrame
v = [100,200,300,400,500]
name = ['John','Bajal','Laya','Ramya','Pannu']
Dict = {'Names':name,'Values':values}
print(Dict)
df = pd.DataFrame(Dict)
print('\n',df)

{'Names': ['John', 'Bajal', 'Laya', 'Ramya', 'Pannu'], 'Values': [100, 200, 300, 400, 500]}

    Names  Values
0   John     100
1  Bajal     200
2   Laya     300
3  Ramya     400
4  Pannu     500

In [ ]:
#List of Dictionary Into a DataFrame
list_of_dict = [{"name":'Aryan','value':'100'},{"name":'Ram','value':'120'}]
df = pd.DataFrame(list_of_dict)
print(df)

    name value
0  Aryan   100
1    Ram   120

In [ ]:
#Reading a CSV File Into a DataFrame
#In a CSV File, all the values are comma separated!
df = pd.read_csv('Titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Reading an Excel File Into a DataFrame
#df = pd.read_excel('Titanic.csv')

In [ ]:
#Shape Function: Specifies the number of columns and rows
print(df.shape)
x=df.shape[0] #rows
y=df.shape[1] #columns
print(x)
print(y)

(999, 12)
999
12

In [ ]:
#To get the total size of the dataset: Total number of elements in the dataset
df.size

11988

In [ ]:
#Describe Function: Describes the entire dataset
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
#Indexing of Columns
print(df['PassengerId'])
type(df['Age'])

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
      ...
994    NaN
995    NaN
996    NaN
997    NaN
998    NaN
Name: PassengerId, Length: 999, dtype: float64

pandas.core.series.Series

In [ ]:
#Checking the null values
print(df.isnull())

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
994         True      True    True   True   True   True   True   True    True
995         True      True    True   True   True   True   True   True    True
996         True      True    True   True   True   True   True   True    True
997         True      True    True   True   True   True   True   True    True
998         True      True    True   True   True   True   True   True    True

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
994   True   True      True
995   True   True      True
996   True   True      True
997   True   True      True
998   True   True      True

[999 rows x 12 columns]

In [ ]:
#Removing the null values
print(df.isnull().sum())
#df.dropna()
'''
how='any': removes all the rows with even a single null values
how='all': removes all the rows which have completely null (NaN) values
inplace='True': makes the deletion of null values permanent
'''

PassengerId    108
Survived       108
Pclass         108
Name           108
Sex            108
Age            285
SibSp          108
Parch          108
Ticket         108
Fare           108
Cabin          795
Embarked       110
dtype: int64

"\nhow='any': removes all the rows with even a single null values\nhow='all': removes all the rows which have completely null (NaN) values\ninplace='True': makes the deletion of null values permanent\n"

In [ ]:
#Techincal Information about the dataset/dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    float64
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(7), object(5)
memory usage: 93.8+ KB

In [ ]:
#Removing the null values
print(df.isnull().sum())
df.dropna(how='all',inplace=True) #Inplace is False by default

PassengerId    108
Survived       108
Pclass         108
Name           108
Sex            108
Age            285
SibSp          108
Parch          108
Ticket         108
Fare           108
Cabin          795
Embarked       110
dtype: int64

In [ ]:
#Aggregation Fucntions: Max, Min, Mean, Sum
print(df['Age'].min())
print(df['Age'].max())

0.42
80.0

In [ ]:
#Checking the DataType of the columns/series
print(df['PassengerId'].dtype)

float64

In [ ]:
#Checking memeory usage
print(df['PassengerId'].memory_usage())

14256

In [ ]:
#Changing the DataType of the columns/series
df['PassengerId'].astype('int16')

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: int16

In [ ]:
import numpy as np
schema = {'PassengerId' : np.int32, 'Pclass': np.int16, 'Embarked':'category'}
df = df.astype(schema)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int32
 1   Survived     891 non-null    float64
 2   Pclass       891 non-null    int16
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    float64
 7   Parch        891 non-null    float64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    category
dtypes: category(1), float64(5), int16(1), int32(1), object(4)
memory usage: 75.8+ KB

In [ ]:
#Priting the preview of the dataset
df.head() #Printing the first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S

In [ ]:
df.head(10) #Printing the first 10 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
5,6,0.0,3,"Moran, Mr. James",male,NaN,0.0,0.0,330877,8.4583,NaN,Q
6,7,0.0,1,"McCarthy, Mr. Timothy J",male,54.0,0.0,0.0,17463,51.8625,E46,S
7,8,0.0,3,"Palsson, Master. Gosta Leonard",male,2.0,3.0,1.0,349909,21.0750,NaN,S
8,9,1.0,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0.0,2.0,347742,11.1333,NaN,S
9,10,1.0,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1.0,0.0,237736,30.0708,NaN,C

In [ ]:
#Used to print all the rows except the last n rows

df.head(-885) #Used to print all the rows except the last 885 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
5,6,0.0,3,"Moran, Mr. James",male,NaN,0.0,0.0,330877,8.4583,NaN,Q

In [ ]:
#Used to print the rows from the last
#df.tail(10) #Prints the last 10 rows
df.tail() #Prints the last 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0.0,2,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,13.00,NaN,S
887,888,1.0,1,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.00,B42,S
888,889,0.0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,2.0,W./C. 6607,23.45,NaN,S
889,890,1.0,1,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.00,C148,C
890,891,0.0,3,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.75,NaN,Q

In [ ]:
#Used to find the specific data of a series from a dataframe
df['Fare'].head(11)

0      7.2500
1     71.2833
2      7.9250
3     53.1000
4      8.0500
5      8.4583
6     51.8625
7     21.0750
8     11.1333
9     30.0708
10    16.7000
Name: Fare, dtype: float64

In [ ]:
#Removing the rows from the DataFrame
#df.drop(0)

In [ ]:
#Removing multiple rows from the DataFrame
#df.drop([0,2,4,6])

In [ ]:
#Accessing the columns from the DataFrame
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
#Removing the columns from the DataFrame
#df.drop('SibSp', axis=1) #Axis=1 when it's a column

In [ ]:
#Removing multiple columns from the DataFrame
#df.drop(['SibSp','Cabin','Embarked'], axis=1)

In [ ]:
#Re-naming a column
#df.rename(columns={'PClass':'Class'})

In [ ]:
#Finding the unique values from given column
print(pd.unique(df['Sex']),'\n')
print(pd.unique(df['Embarked']))

['male' 'female']

['S', 'C', 'Q', NaN]
Categories (3, object): ['C', 'Q', 'S']

In [ ]:
#Accessing Multiple Columns from the DataSet: Series needs to be converted into a dataframe to access the columns
df[['PassengerId','Sex','Age']]

     PassengerId     Sex   Age
0              1    male  22.0
1              2  female  38.0
2              3  female  26.0
3              4  female  35.0
4              5    male  35.0
..           ...     ...   ...
886          887    male  27.0
887          888  female  19.0
888          889  female   NaN
889          890    male  26.0
890          891    male  32.0

[891 rows x 3 columns]

In [ ]:
#Group by function in Python
df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
#Find how many males and females
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [ ]:
#Find how many survived
df['Survived'].value_counts()

0.0    549
1.0    342
Name: Survived, dtype: int64

In [ ]:
#The way to find the missing value count
pd.isna(df).sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#Loc and Iloc function
#Iloc (Index Location)
#Suppose we only want to work on the first 100 rows (analyze,compare etc.)

#Used to analyze and work upon the specific set of rows and columns from a certain dataframe
df.iloc[0:101,0:3] #Syntax for the rows: (Start:End:Step_Size), (Start:End:Step_Size) :Syntax for the columns

     PassengerId  Survived  Pclass
0              1       0.0       3
1              2       1.0       1
2              3       1.0       3
3              4       1.0       1
4              5       0.0       3
..           ...       ...     ...
96            97       0.0       1
97            98       1.0       1
98            99       1.0       2
99           100       0.0       2
100          101       0.0       3

[101 rows x 3 columns]

In [ ]:
#Loc Function: Location Function is used to get hold of specific value ranges in certain series of the dataframe
df.loc[0:20,['Age','Parch']]

     Age  Parch
0   22.0    0.0
1   38.0    0.0
2   26.0    0.0
3   35.0    0.0
4   35.0    0.0
5    NaN    0.0
6   54.0    0.0
7    2.0    1.0
8   27.0    2.0
9   14.0    0.0
10   4.0    1.0
11  58.0    0.0
12  20.0    0.0
13  39.0    5.0
14  14.0    0.0
15  55.0    0.0
16   2.0    1.0
17   NaN    0.0
18  31.0    0.0
19   NaN    0.0
20  35.0    0.0

In [ ]:
#Analysis of the Titanic Dataset

#Number/Count of people who were older than 18 years of age on the ship
age=df['Age']

#Average age of passengers on the ship
print(age.mean())

c1 = age>18
print(c1.value_counts())
print('\n',c1.sum())

29.69911764705882
True     575
False    316
Name: Age, dtype: int64

 575

In [ ]:
#The people who were older than 18 years of age on the ship
df[c1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0.0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0.0,5.0,382652,29.1250,NaN,Q
886,887,0.0,2,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,13.0000,NaN,S
887,888,1.0,1,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.0000,B42,S
889,890,1.0,1,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,C148,C
890,891,0.0,3,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.7500,NaN,Q

In [ ]:
#Number of people in 1st Class
cla = df['Pclass']
c2 = (cla==1.0)
c2.sum()

216

In [ ]:
#Number of people who've survived
sur = df['Survived']
c2 = (sur==1.0)
c2.sum()

342

In [ ]:
#Multiple Conditions
c3 = (cla==3.0) & (age>18)
#Display all the rows with class 3 and age>18: df[c3]
c3.sum()

261

In [ ]:
#Printing only the particular columns with the condition
df[c3][['Name','Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
2                               Heikkinen, Miss. Laina  26.0
4                             Allen, Mr. William Henry  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
12                      Saundercock, Mr. William Henry  20.0
..                                                 ...   ...
881                                 Markun, Mr. Johann  33.0
882                       Dahlberg, Miss. Gerda Ulrika  22.0
884                             Sutehall, Mr. Henry Jr  25.0
885               Rice, Mrs. William (Margaret Norton)  39.0
890                                Dooley, Mr. Patrick  32.0

[261 rows x 2 columns]

In [ ]:
#Find the passengers who're either in 2nd Class or Embarked S
emb = df['Embarked']
c4 = (emb=='S') | (cla==2.0)
print(c4.sum())
df[c4][['Pclass','Embarked']]

664

     Pclass Embarked
0         3        S
2         3        S
3         1        S
4         3        S
6         1        S
..      ...      ...
883       2        S
884       3        S
886       2        S
887       1        S
888       3        S

[664 rows x 2 columns]

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,13.0000,NaN,S
887,888,1.0,1,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.0000,B42,S
888,889,0.0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,2.0,W./C. 6607,23.4500,NaN,S
889,890,1.0,1,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,C148,C
890,891,0.0,3,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.7500,NaN,Q

In [ ]:
#Fare is less than 100 & Embarked is either S or C
emb = df['Embarked']
fare = df['Fare']
cz = ((emb=='S') | (emb=='C')) & (fare<100)
print(cz.sum())
#df[cz]

759

In [ ]:
#Fare is less than 100 & Embarked is either S or C by using isin function: It performs the OR operation
#df[(df['Fare']<100) & (df['Embarked'].isin(['S','C']))]

In [ ]:
#df[(df['Pclass'].isin([1.0,2.0]))]

In [ ]:
#Sorting Function: by --> specify the column name
#Ascending: df.sort_values(by = 'Fare')
#Desending: df.sort_values(by = 'Fare',ascending=False)

In [ ]:
df_sample = pd.read_csv('nba_sample.csv')
df_sample

,player_name,team_abbreviation,age,player_height,player_weight,college,country
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA
1,Gaylon Nickerson,WAS,28,190.50,86.182480,Northwestern Oklahoma,USA
2,George Lynch,VAN,26,203.20,103.418976,North Carolina,USA
3,George McCloud,LAL,30,203.20,102.058200,Florida State,USA
4,George Zidek,DEN,23,213.36,119.748288,UCLA,USA
...,...,...,...,...,...,...,...
12839,Joel Embiid,PHI,29,213.36,127.005760,Kansas,Cameroon
12840,John Butler Jr.,POR,20,213.36,86.182480,Florida State,USA
12841,John Collins,ATL,25,205.74,102.511792,Wake Forest,USA
12842,Jericho Sims,NYK,24,208.28,113.398000,Texas,USA
12843,JaMychal Green,GSW,33,205.74,102.965384,Alabama,USA

In [ ]:
#Calculate the BMI of the players
#BMI=Weight(kg)/Height(m^2)
df_sample["player_height_m"] = df_sample['player_height']/100
df_sample["BMI"] = df_sample['player_weight']/(df_sample['player_height_m']**2)

In [ ]:
'''Create a new column with the name “BMI Evaluation”. Assign the BMI status based on the following condition,


BMI <= 18.4 - "Underweight"

BMI <= 24.9 - "Healthy"

BMI <= 29.9 - "Over Weight"

BMI <= 34.9 - "Severely Over Weight"

BMI <= 39.9 - "Obese"
39.9 - "Severely Obese."
'''

def evaluate_bmi(bmi):
    if bmi <= 18.4:
        return "Underweight"
    elif bmi <= 24.9:
        return "Healthy"
    elif bmi <= 29.9:
        return "Overweight"
    elif bmi <= 34.9:
        return "Severely Overweight"
    elif bmi <= 39.9:
        return "Obese"
    else:
        return "Severely Obese"

# Apply the function to create the "BMI Evaluation" column
df_sample["BMI Evaluation"] = df_sample["BMI"].apply(evaluate_bmi)
df_sample

,player_name,team_abbreviation,age,player_height,player_weight,college,country,player_height_m,BMI,BMI Evaluation
0,Randy Livingston,HOU,22,193.04,94.800728,Louisiana State,USA,1.9304,25.439997,Overweight
1,Gaylon Nickerson,WAS,28,190.50,86.182480,Northwestern Oklahoma,USA,1.9050,23.748109,Healthy
2,George Lynch,VAN,26,203.20,103.418976,North Carolina,USA,2.0320,25.046833,Overweight
3,George McCloud,LAL,30,203.20,102.058200,Florida State,USA,2.0320,24.717270,Healthy
4,George Zidek,DEN,23,213.36,119.748288,UCLA,USA,2.1336,26.305303,Overweight
...,...,...,...,...,...,...,...,...,...,...
12839,Joel Embiid,PHI,29,213.36,127.005760,Kansas,Cameroon,2.1336,27.899564,Overweight
12840,John Butler Jr.,POR,20,213.36,86.182480,Florida State,USA,2.1336,18.931847,Healthy
12841,John Collins,ATL,25,205.74,102.511792,Wake Forest,USA,2.0574,24.217893,Healthy
12842,Jericho Sims,NYK,24,208.28,113.398000,Texas,USA,2.0828,26.140281,Overweight
12843,JaMychal Green,GSW,33,205.74,102.965384,Alabama,USA,2.0574,24.325052,Healthy

In [ ]:
#Group by function: Can be used in association with the aggregate functions
df.groupby(by=['Pclass',"Sex"]).count()

               PassengerId  Survived  Name  Age  SibSp  Parch  Ticket  Fare  \
Pclass Sex
1      female           94        94    94   85     94     94      94    94
       male            122       122   122  101    122    122     122   122
2      female           76        76    76   74     76     76      76    76
       male            108       108   108   99    108    108     108   108
3      female          144       144   144  102    144    144     144   144
       male            347       347   347  253    347    347     347   347

               Cabin  Embarked
Pclass Sex
1      female     81        92
       male       95       122
2      female     10        76
       male        6       108
3      female      6       144
       male        6       347

In [ ]:
#Sum of fare spent by females according to the specific classes
df.groupby(by=['Pclass','Sex'])['Fare'].sum()

Pclass  Sex
1       female    9975.8250
        male      8201.5875
2       female    1669.7292
        male      2132.1125
3       female    2321.1086
        male      4393.5865
Name: Fare, dtype: float64

In [ ]:
#Mean of fare spent by females according to the specific classes sorted in ascending order
df.groupby(by=['Pclass','Sex'])['Fare'].mean().sort_values()

Pclass  Sex
3       male       12.661633
        female     16.118810
2       male       19.741782
        female     21.970121
1       male       67.226127
        female    106.125798
Name: Fare, dtype: float64

In [ ]:
#To specify multiple aggregation functions
df.groupby(by=['Pclass','Sex'])['Fare'].agg(['max','min','sum','mean','count'])

                    max      min        sum        mean  count
Pclass Sex
1      female  512.3292  25.9292  9975.8250  106.125798     94
       male    512.3292   0.0000  8201.5875   67.226127    122
2      female   65.0000  10.5000  1669.7292   21.970121     76
       male     73.5000   0.0000  2132.1125   19.741782    108
3      female   69.5500   6.7500  2321.1086   16.118810    144
       male     69.5500   0.0000  4393.5865   12.661633    347

In [ ]:
#To add indices
df.groupby(by=['Pclass','Sex'])['Fare'].agg(['max','min','sum','mean','count']).reset_index()

   Pclass     Sex       max      min        sum        mean  count
0       1  female  512.3292  25.9292  9975.8250  106.125798     94
1       1    male  512.3292   0.0000  8201.5875   67.226127    122
2       2  female   65.0000  10.5000  1669.7292   21.970121     76
3       2    male   73.5000   0.0000  2132.1125   19.741782    108
4       3  female   69.5500   6.7500  2321.1086   16.118810    144
5       3    male   69.5500   0.0000  4393.5865   12.661633    347

In [ ]:
#Specifying the aggregation functions for the columns
df.groupby(by=["Pclass",'Sex']).agg({"Age":"mean","Fare":"sum","PassengerId":"count"})

                     Age       Fare  PassengerId
Pclass Sex
1      female  34.611765  9975.8250           94
       male    41.281386  8201.5875          122
2      female  28.722973  1669.7292           76
       male    30.740707  2132.1125          108
3      female  21.750000  2321.1086          144
       male    26.507589  4393.5865          347